### ISSUE TITLE
Scenario tests in liberty failing due to AttributeError

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/neutron-lbaas#23]
The six scenario tests in liberty are failing due to error below:

```
Traceback (most recent call last):
  File "/home/buildbot/neutron-lbaas/neutron_lbaas/tests/tempest/v2/scenario/base_tls.py", line 35, in setUp
    super(BaseTestCaseTLS, self).setUp()
  File "/home/buildbot/neutron-lbaas/neutron_lbaas/tests/tempest/v2/scenario/base.py", line 86, in setUp
    self._create_security_group_for_test()
  File "/home/buildbot/neutron-lbaas/neutron_lbaas/tests/tempest/v2/scenario/base.py", line 147, in _create_security_group_for_test
    tenant_id=self.tenant_id)
AttributeError: 'TestLoadBalancerTLS' object has no attribute 'tenant_id'
```

After adding an explicit line to set the tenant_id before line 147, I can get five of the six tests to pass in undercloud. The call I add is as follows:

`self.tenant_id = self.manager.identity_client.tenant_id`

```
../../../../../../../testlab/f5-openstack-lbaasv2-driver/::TestHealthMonitorBasic::test_health_monitor_basic <- ../../buildbot/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/test.py PASSED
../../../../../../../testlab/f5-openstack-lbaasv2-driver/::TestListenerBasic::test_listener_basic <- ../../buildbot/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/test.py PASSED
../../../../../../../testlab/f5-openstack-lbaasv2-driver/::TestLoadBalancerBasic::test_load_balancer_basic <- ../../buildbot/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/test.py PASSED
../../../../../../../testlab/f5-openstack-lbaasv2-driver/::TestLoadBalancerTLS::test_load_balancer_tls <- ../../buildbot/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/test.py PASSED
../../../../../../../testlab/f5-openstack-lbaasv2-driver/::TestLoadBalancerTLS::test_load_balancer_tls <- ../../buildbot/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/test.py PASSED
../../../../../../../testlab/f5-openstack-lbaasv2-driver/::TestSessionPersistence::test_session_persistence <- ../../buildbot/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/test.py FAILED
```

This must be some failure to execute the resource_setup method. It looks as though it is not being called in the base class.

**Comment by pjbreaux** [comment]
@dflanigan: Merging to master may not make sense for this repo. I'd like for the team to weigh in and decide if we should close this issue outright.
