### ISSUE TITLE
mitaka scenario tests intermittently fail due to ServerFault error

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/neutron-lbaas#42]
@dflanigan: please put this in Jira, so we can track a fix.

Nearly all of the six scenario tests have failed at some point in time during the nightly runs due to this issue. The tempest output for the error is rather vague, but if we can capture the neutron server and f5-openstack-agent logs, we'll likely be able to diagnose it quickly. In the error below, it appears as though we are doing a GET on the loadbalancer, and during that step, we get the error and the test begins to teardown.

```
http://10.190.4.139:9696/v2.0/lbaas/loadbalancers/cff51063-a18b-43d2-b33d-b134b00fb66d 0.047s
2017-07-02 01:23:45,091 30006 INFO     [tempest.lib.common.rest_client] Request (TestListenerBasic:test_listener_basic): 200 GET http://10.190.4.139:9696/v2.0/lbaas/loadbalancers/cff51063-a18b-43d2-b33d-b134b00fb66d 0.062s
2017-07-02 01:25:13,428 30006 INFO     [tempest.lib.common.rest_client] Request (TestListenerBasic:_run_cleanups): 204 DELETE 
```

The error message is shown below:

```
Traceback (most recent call last):
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/scenario/base.py", line 340, in _cleanup_load_balancer
    self._wait_for_load_balancer_status(load_balancer_id, delete=True)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/scenario/base.py", line 458, in _wait_for_load_balancer_status
    load_balancer_id)
File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/clients/load_balancers_client.py", line 40, in get_load_balancer
    resp, body = self.get(url)
File "/home/jenkins/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 274, in get
    return self.request('GET', url, extra_headers, headers)
File "/home/jenkins/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 641, in request
    resp, resp_body)
File "/home/jenkins/neutron-lbaas/.tox/scenariov2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 760, in _error_checker
    message=message)
tempest.lib.exceptions.ServerFault: Got server fault
Details: Request Failed: internal server error while processing your request.
```

**Comment by pjbreaux** [comment]
After recreating the error, this looks possibly like an internal neutron (sqlalchemy) issue. In the server.log for neutron, I see:

```
2017-07-17 11:21:22.393 24434 INFO neutron.wsgi [-] (24434) accepted ('10.190.25.177', 51860)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource [req-4c65b434-d75b-4663-b462-6c6c1c7ea36c f4ed956cab23459c88702e00e4e0e19b 3aa4f4505a714b1988533c478200b33c - - -] show failed
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource Traceback (most recent call last):
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/resource.py", line 83, in resource
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     result = method(request=request, **args)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 146, in wrapper
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     ectxt.value = e.inner_exc
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 195, in __exit__
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     six.reraise(self.type_, self.value, self.tb)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 136, in wrapper
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     return f(*args, **kwargs)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 361, in show
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     parent_id=parent_id),
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron/api/v2/base.py", line 311, in _item
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     obj = obj_getter(request.context, id, **kwargs)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py", line 560, in get_loadbalancer
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     return self.db.get_loadbalancer(context, id).to_api_dict()
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/db/loadbalancer/loadbalancer_dbv2.py", line 268, in get_loadbalancer
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     lb_db = self._get_resource(context, models.LoadBalancer, id)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib/python2.7/site-packages/neutron_lbaas/db/loadbalancer/loadbalancer_dbv2.py", line 73, in _get_resource
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     context.session.refresh(resource)
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1367, in refresh
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource     instance_str(instance))
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource InvalidRequestError: Could not refresh instance '<LoadBalancer at 0x72422d0>'
2017-07-17 11:21:22.510 24434 ERROR neutron.api.v2.resource
```

**Comment by pjbreaux** [comment]
We could simply retry...
