### ISSUE TITLE
tempest.lib.exceptions.BadRequest occurs in nightly in LoadBalancersTestJSON.test_create_load_balancer_provider_flavor_conflict

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/neutron-lbaas#47]
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_load_balancers_non_admin.py", line 301, in test_create_load_balancer_provider_flavor_conflict
    provider="NO_SUCH_PROVIDER")
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 445, in assertThat
    mismatch_error = self._matchHelper(matchee, matcher, message, verbose)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 495, in _matchHelper
    mismatch = matcher.match(matchee)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/matchers/_exception.py", line 108, in match
    mismatch = self.exception_matcher.match(exc_info)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/matchers/_higherorder.py", line 62, in match
    mismatch = matcher.match(matchee)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 426, in match
    reraise(*matchee)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/matchers/_exception.py", line 101, in match
    result = matchee()
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 982, in __call__
    return self._callable_object(*self._args, **self._kwargs)
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/clients/load_balancers_client.py", line 48, in create_load_balancer
    resp, body = self.post('v2.0/lbaas/loadbalancers', post_body)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 259, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 641, in request
    resp, resp_body)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 699, in _error_checker
    raise exceptions.BadRequest(resp_body, resp=resp)
tempest.lib.exceptions.BadRequest: Bad request
Details: {u'type': u'HTTPBadRequest', u'detail': u'', u'message': u"Unrecognized attribute(s) 'flavor_id'"}
```
### Associated sums:
* `md5sum:5480a7bc286b8e08f56ad4ae62e7d1c2`
* `reduced(md5sum):aef2a213b2870f4676a0d8b17fdf8908`

### Assocaited Tests:

* `openstack_driver_liberty_11.5.4-undercloud-vxlan.79.consoleText.LoadBalancersTestJSON.test_create_load_balancer_provider_flavor_conflict`
* `openstack_driver_liberty_12.1.1-undercloud-vxlan.99.consoleText.LoadBalancersTestJSON.test_create_load_balancer_provider_flavor_conflict`
* `openstack_driver_liberty_11.6.1-undercloud-vxlan.82.consoleText.LoadBalancersTestJSON.test_create_load_balancer_provider_flavor_conflict`
#### Agent Version
* Liberty - 1b032716919cd36ee8bb849887b587acc63e725a

#### Driver version
* Liberty - f97d6bc395c932b31fb029ee8b964e679233ef2f

**Comment by ssorenso** [comment]
Additional tests/sums:
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_load_balancers_non_admin.py", line 292, in test_create_load_balancer_invalid_flavor_field
    flavor_id="NO_SUCH_FLAVOR")
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 445, in assertThat
    mismatch_error = self._matchHelper(matchee, matcher, message, verbose)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 495, in _matchHelper
    mismatch = matcher.match(matchee)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/matchers/_exception.py", line 108, in match
    mismatch = self.exception_matcher.match(exc_info)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/matchers/_higherorder.py", line 62, in match
    mismatch = matcher.match(matchee)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 426, in match
    reraise(*matchee)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/matchers/_exception.py", line 101, in match
    result = matchee()
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 982, in __call__
    return self._callable_object(*self._args, **self._kwargs)
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/clients/load_balancers_client.py", line 48, in create_load_balancer
    resp, body = self.post('v2.0/lbaas/loadbalancers', post_body)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 259, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 641, in request
    resp, resp_body)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/tempest/lib/common/rest_client.py", line 699, in _error_checker
    raise exceptions.BadRequest(resp_body, resp=resp)
tempest.lib.exceptions.BadRequest: Bad request
Details: {u'type': u'HTTPBadRequest', u'detail': u'', u'message': u"Unrecognized attribute(s) 'flavor_id'"}
```
Tests:
* `openstack_driver_liberty_11.5.4-undercloud-vxlan.79.consoleText.LoadBalancersTestJSON.test_create_load_balancer_invalid_flavor_field`
* `openstack_driver_liberty_12.1.1-undercloud-vxlan.99.consoleText.LoadBalancersTestJSON.test_create_load_balancer_invalid_flavor_field`
* `openstack_driver_liberty_11.6.1-undercloud-vxlan.82.consoleText.LoadBalancersTestJSON.test_create_load_balancer_invalid_flavor_field`
sums:75b6cad4773624e2c5a39db3d2d4687a
