### ISSUE TITLE
Import failure in f5lbaasdriver

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/neutron-lbaas#5]
F5 used what is now called the 'master_pre_upstream' branch to create the driver shim for inclusion in community neutron-lbaas.  The code was reviewed and accepted, so we merged master to fresh our fork with community.  The F5-specific code is different between upstream and our original fork.

**Comment by mattgreene** [comment]
```
2016-08-04 13:10:44.823 33304 CRITICAL neutron [-] AttributeError: 'module' object has no attribute 'v2'
2016-08-04 13:10:44.823 33304 ERROR neutron Traceback (most recent call last):
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/bin/neutron-server", line 10, in <module>
2016-08-04 13:10:44.823 33304 ERROR neutron     sys.exit(main_wsgi_eventlet())
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/cmd/eventlet/server/__init__.py", line 19, in main_wsgi_eventlet
2016-08-04 13:10:44.823 33304 ERROR neutron     wsgi_eventlet.main()
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/server/wsgi_eventlet.py", line 50, in main
2016-08-04 13:10:44.823 33304 ERROR neutron     server.boot_server(_eventlet_wsgi_server)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/server/__init__.py", line 35, in boot_server
2016-08-04 13:10:44.823 33304 ERROR neutron     server_func()
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/server/wsgi_eventlet.py", line 27, in _eventlet_wsgi_server
2016-08-04 13:10:44.823 33304 ERROR neutron     neutron_api = service.serve_wsgi(service.NeutronApiService)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 106, in serve_wsgi
2016-08-04 13:10:44.823 33304 ERROR neutron     LOG.exception(_LE('Unrecoverable error: please check log '
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 195, in __exit__
2016-08-04 13:10:44.823 33304 ERROR neutron     six.reraise(self.type_, self.value, self.tb)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 103, in serve_wsgi
2016-08-04 13:10:44.823 33304 ERROR neutron     service.start()
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 76, in start
2016-08-04 13:10:44.823 33304 ERROR neutron     self.wsgi_app = _run_wsgi(self.app_name)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/service.py", line 208, in _run_wsgi
2016-08-04 13:10:44.823 33304 ERROR neutron     app = config.load_paste_app(app_name)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/neutron/common/config.py", line 252, in load_paste_app
2016-08-04 13:10:44.823 33304 ERROR neutron     app = deploy.loadapp("config:%s" % config_path, name=app_name)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
2016-08-04 13:10:44.823 33304 ERROR neutron     return loadobj(APP, uri, name=name, **kw)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
2016-08-04 13:10:44.823 33304 ERROR neutron     return context.create()
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
2016-08-04 13:10:44.823 33304 ERROR neutron     return self.object_type.invoke(self)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 144, in invoke
2016-08-04 13:10:44.823 33304 ERROR neutron     **context.local_conf)
2016-08-04 13:10:44.823 33304 ERROR neutron   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
```
