### ISSUE TITLE
test_health_monitors_non_admin.py:test_update_health_monitor_empty_empty_http_method test Failure due to mismatchError

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/neutron-lbaas#50]
#### Traceback:
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_health_monitors_non_admin.py", line 499, in test_update_health_monitor_empty_empty_http_method
    hm.get('id'), http_method='')
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method TestHealthMonitors._update_health_monitor of <neutron_lbaas.tests.tempest.v2.api.test_health_monitors_non_admin.TestHealthMonitors.test_update_health_monitor_empty_empty_http_method[negative] id=0x7f9adbbd6250>> returned {u'admin_state_up': True, u'tenant_id': u'00f34410e13349418cfa9be1b628d98f', u'expected_codes': u'200', u'delay': 3, u'http_method': u'', u'max_retries': 10, u'timeout': 5, u'pools': [{u'id': u'd7e301c0-2a01-481a-b1da-43f3a06cb514'}], u'url_path': u'/', u'id': u'2f784424-415f-4b74-8c72-e8d77a205cfe', u'type': u'HTTP'}
```

#### Tests:
* `openstack_driver_liberty_11.5.4-undercloud-vxlan.81.consoleText`
  * type: failures
  * test: `TestHealthMonitors.test_update_health_monitor_empty_empty_http_method`
  * sum: md5sum:0156c75f64a98cfa74ff80a8d770cfc9

**Comment by ssorenso** [comment]
Very similar error in the same library:
```
```
Tests:
* `openstack_driver_liberty_11.5.4-undercloud-vxlan.82.consoleText`
  * Type: failures
  * Test: `TestHealthMonitors.test_create_health_monitor_invalid_http_method`
* md5sum:0ff3ac548d78762d1cdf0b8a9446fe63
