### ISSUE TITLE
tests/tempest/v2/api/test_listeners_admin.py:test_create_listener_empty_tenant_id test failure due to MismatchError

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/neutron-lbaas#54]
#### Tracebacks:
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_admin.py", line 67, in test_create_listener_empty_tenant_id
    **create_new_listener_kwargs)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method type._create_listener of <class 'neutron_lbaas.tests.tempest.v2.api.test_listeners_admin.ListenersTestJSON'>> returned {u'loadbalancers': [{u'id': u'dec0e759-8726-4cc4-b5d5-715a315f70ff'}], u'tenant_id': u'', u'sni_container_refs': [], u'default_pool_id': None, u'description': u'', u'default_tls_container_ref': None, u'protocol_port': 8081, u'id': u'766e5f7a-b3f2-420e-95c3-3b64e90f0a09', u'protocol': u'HTTP', u'admin_state_up': True, u'connection_limit': -1, u'name': u''}

```
#### Tests:
`openstack_driver_liberty_11.5.4-undercloud-vxlan.82.consoleText`
  * Type: Failures
  * Test: `ListenersTestJSON.test_create_listener_empty_tenant_id`
  * Sum: md5sum:`060bfa020b51198fea85397671f2a429`

**Comment by ssorenso** [comment]
Confirmed again in mitaka:
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_admin.py", line 67, in test_create_listener_empty_tenant_id
    **create_new_listener_kwargs)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method type._create_listener of <class 'neutron_lbaas.tests.tempest.v2.api.test_listeners_admin.ListenersTestJSON'>> returned {u'loadbalancers': [{u'id': u'dec0e759-8726-4cc4-b5d5-715a315f70ff'}], u'tenant_id': u'', u'sni_container_refs': [], u'default_pool_id': None, u'description': u'', u'default_tls_container_ref': None, u'protocol_port': 8081, u'id': u'766e5f7a-b3f2-420e-95c3-3b64e90f0a09', u'protocol': u'HTTP', u'admin_state_up': True, u'connection_limit': -1, u'name': u''
```
Tests:

`openstack_driver_mitaka_12.1.2-overcloud.4.consoleText`
  * Type: Failures
  * Test: `MemberSubnetTestJSON.test_member_selfips`
  * Sum: md5sum:`0655e399d2785026aba399a9ab6f2923`

**Comment by ssorenso** [comment]
```
Traceback (most recent call last):
  File "/home/jenkins/neutron-lbaas/neutron_lbaas/tests/tempest/v2/api/test_listeners_admin.py", line 67, in test_create_listener_empty_tenant_id
    **create_new_listener_kwargs)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 434, in assertRaises
    self.assertThat(our_callable, matcher)
  File "/home/jenkins/neutron-lbaas/.tox/apiv2/local/lib/python2.7/site-packages/testtools/testcase.py", line 447, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: <bound method type._create_listener of <class 'neutron_lbaas.tests.tempest.v2.api.test_listeners_admin.ListenersTestJSON'>> returned {u'loadbalancers': [{u'id': u'dec0e759-8726-4cc4-b5d5-715a315f70ff'}], u'tenant_id': u'', u'sni_container_refs': [], u'default_pool_id': None, u'description': u'', u'default_tls_container_ref': None, u'protocol_port': 8081, u'id': u'766e5f7a-b3f2-420e-95c3-3b64e90f0a09', u'protocol': u'HTTP', u'admin_state_up': True, u'connection_limit': -1, u'name': u''
```

`openstack_driver_liberty_12.1.2-undercloud-vxlan.1.consoleText`
  * Type: failures
  * Test: `TestHealthMonitors.test_create_health_monitor_invalid_url_path`
  * Sum: md5sum:`077ef8ee88d1eca88ddb37e1c66fa568`
